---
services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=${APP_URL}
      - APP_HOST=${APP_HOST}
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=pgsql
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - .:/var/www/html
    networks:
      - traefik_network

  laravel-nginx:
    image: nginx:latest
    container_name: laravel-nginx
    depends_on:
      - laravel-app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    networks:
      - traefik_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.laravel-app.rule=PathPrefix(`/laravel-app`)
      - traefik.http.middlewares.laravel-app-stripprefix.stripprefix.prefixes=/laravel-app
      - traefik.http.routers.laravel-app.middlewares=laravel-app-stripprefix
      - traefik.http.routers.laravel-app.entrypoints=web
      - traefik.http.services.laravel-app.loadbalancer.server.port=80

networks:
  traefik_network:
    external: true
