---
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: first-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.postgres.entrypoints=postgres"
      - "traefik.tcp.routers.postgres.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.postgres.service=postgres"
      - "traefik.tcp.services.postgres.loadbalancer.server.port=5432"
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - 8082:80
    depends_on:
      - postgres
    networks:
      - traefik_network
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgadmin.rule=Host(`app.benaja-bendo.fr`)
      - traefik.http.routers.pgadmin.entrypoints=pgadmin
      - traefik.http.services.pgadmin.loadbalancer.server.port=8082
networks:
  traefik_network:
    external: true