---
services:
  traefik:
    image: traefik:v3.2.0
    container_name: traefik-demo-1
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN:-}
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL:-}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/acme.json:/acme.json
    networks:
      - traefik_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-dashboard.rule=Host(`app.benaja-bendo.fr`)
      - traefik.http.routers.traefik-dashboard.entryPoints=dashboard
      - traefik.http.routers.traefik-dashboard.service=api@internal
      - traefik.http.routers.traefik-dashboard.tls.certResolver=letsencrypt
      - traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080

networks:
  traefik_network:
    external: true
