global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG

api:
  dashboard: true
  insecure: false

entryPoints:
  dashboard:
    address: :8080
  web:
    address: :80
    http:
     redirections:
       entryPoint:
         to: websecure
         scheme: https
  websecure:
    address: :443
    http:
      tls:
        certResolver: letsencrypt
  postgres:
    address: :5432
  pgadmin:
    address: :8082
  mongo:
    address: :27017
  mongo-express:
    address: :8081
  
certificatesResolvers:
  letsencrypt:
    acme:
      email: "benaja.bendo02@gmail.com"
      storage: "acme.json"
      httpChallenge:
        entryPoint: "web"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
