---
services:
  node-api:
    container_name: node-api-service
    build: .
    restart: always
    environment:
      - PORT=3000
    networks:
      - traefik_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.node-api.rule=Host(`${SERVER_IP}`)
      # - traefik.http.routers.node-api.rule=PathPrefix(`/node-api`)
      # - traefik.http.middlewares.node-api-stripprefix.stripprefix.prefixes=/node-api
      # - traefik.http.routers.node-api.middlewares=node-api-stripprefix
      # - traefik.http.routers.node-api.entrypoints=web
      - traefik.http.routers.node-api.entrypoints=websecure
      - traefik.http.routers.node-api.tls.certresolver=letsencrypt
      - traefik.http.services.node-api.loadbalancer.server.port=3000

    expose:
      - 3000
networks:
  traefik_network:
    external: true