---
services:
  caddy:
      image: caddy:latest
      container_name: caddy-service
      networks:
        - traefik_network
      labels:
        - traefik.enable=true
        - traefik.http.routers.caddy.rule=PathPrefix(`/caddy`)
        - traefik.http.routers.caddy.entrypoints=web
        - traefik.http.middlewares.caddy-stripprefix.stripprefix.prefixes=/caddy
        - traefik.http.routers.caddy.middlewares=caddy-stripprefix
        #- traefik.http.routers.caddy-secure.rule=PathPrefix(`/caddy`)
        #- traefik.http.routers.caddy-secure.entrypoints=websecure
        #- traefik.http.routers.caddy-secure.tls=true
        #- traefik.http.routers.caddy-secure.tls.certresolver=cloudflare
networks:
  traefik_network:
    external: true